package work.customannotatition;


import work.configuration.Configuration;
import work.exampleclasses.Book;
import work.exampleclasses.Car;
import work.exampleclasses.Person;

public class LombokExamples {

    public static void main(String[] args) {

        //Constructor with required fields (final or @NonNull)
        Person emptyClass = new Person();
        System.out.println("[@Data annotation] result Constructor:");
        System.out.println(emptyClass);
        System.out.println("-------------------------------");

        //Setter
        //public String toString() {
        //        return "Person(" +
        //                "name=" + name + ", " +
        //                "age=" + age + ", " +
        //                "email=" + email +
        //                ")";
        //    }
        Person person = new Person();
        person.setName("Ivan");
        person.setAge(18);
        person.setEmail("ivan@mail.com");
        System.out.println("[@Data annotation] result Setter and toString:");
        System.out.println(person);
        System.out.println("-------------------------------");

        //Getter
        String name = person.getName();
        int age = person.getAge();
        String email = person.getEmail();
        System.out.println("[@Data annotation] result Getter:");
        System.out.println("name field: " + name);
        System.out.println("age field: " + age);
        System.out.println("email field: " + email);
        System.out.println("-------------------------------");

        //equals
        Person person2 = new Person();
        person2.setName("Ivan");
        person2.setAge(18);
        person2.setEmail("ivan@mail.com");
        boolean result = person2.equals(person);
        System.out.println("[@Data annotation] equals method result:");
        System.out.println("person equals person2, boolean result: " + result);
        System.out.println("-------------------------------");

        //hashCode
        int hashCode = person.hashCode();
        System.out.println("[@Data annotation] hash code method result:");
        System.out.println("person hash code: " + hashCode);
        int hashCode2 = person2.hashCode();
        System.out.println("person2 hash code: " + hashCode2);
        boolean resultEquals = hashCode == hashCode2;
        System.out.println("person hash code equals person2 hash code, boolean result: " + resultEquals);
        System.out.println("-------------------------------");

        //@RequiredArgsConstructor
        Car newCar = new Car("Lexus", "LS470");
        System.out.println("[@RequiredArgsConstructor annotation] result Constructor annotation:");
        System.out.println("You can create a new Object with final fields only us: new Car(Lexus, LS470)");
        System.out.println("-------------------------------");

        //The constructor generated by @AllArgsConstructor.
        //Accepts values for all fields of the class.
        //public Book(String title, String author, int pages, double price) {
        //    this.title = title;
        //    this.author = author;
        //    this.pages = pages;
        //    this.price = price;
        Book book = new Book("1984", "George Orwell", 328, 15.99);

        //Lombok will automatically generate an internal static House class.House Builder with methods for setting
        // each field and the build() method, which will return the finished House object.
        //
        // House house = House.builder()
        //                .address("ул. Ленина, 10")
        //                .rooms(4)
        //                .area("120 кв.м")
        //                .price(6_500_000)
        //                .build();

        //The Lombok @Setter and @Getter annotations automatically generate methods for setting and retrieving class field values.
        //
        //    Getter for field id
        //    public int getId() {
        //        return id;
        //    }
        //
        //    Setter for field id
        //    public void setId(int id) {
        //        this.id = id;
        //    }
        //
        //    Getter for field name
        //    public String getName() {
        //        return name;
        //    }
        //
        //    Setter for field name
        //    public void setName(String name) {
        //        this.name = name;
        //    }

        //Annotation @Accessors(chain = true) from Lombok allows you to generate chained setters
        Configuration config = new Configuration()
                    .setHost("localhost")
                    .setPort(5432)
                    .setUsername("admin")
                    .setPassword("secret");
        System.out.println("[@Accessors annotation] result: " + config);
    }
}
